// src/utils/constants.js

export const current_definition = {
  temperature_2m: "Temperature",
  relative_humidity_2m: "Humidity",
  apparent_temperature: "Feels like",
  is_day: "Day/Night",
  precipitation: "Precipitation",
  rain: "Rain",
  showers: "Showers",
  snowfall: "Snowfall",
  cloud_cover: "Cloud coverage",
  pressure_msl: "Sea-level pressure",
  surface_pressure: "Surface pressure",
  wind_speed_10m: "Wind speed",
  wind_direction_10m: "Wind direction",
  wind_gusts_10m: "Wind gusts",
};

export const weatherDescriptions = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Light Drizzle",
    53: "Moderate Drizzle",
    55: "Dense Drizzle",
    56: "Light Freezing Drizzle",
    57: "Dense Freezing Drizzle",
    61: "Slight Rain",
    63: "Moderate Rain",
    65: "Heavy Rain",
    66: "Light Freezing Rain",
    67: "Heavy Freezing Rain",
    71: "Slight Snowfall",
    73: "Moderate Snowfall",
    75: "Heavy Snowfall",
    77: "Snow grains",
    80: "Slight Rain showers",
    81: "Moderate Rain showers",
    82: "Violent Rain showers",
    85: "Slight Snow showers",
    86: "Heavy Snow showers",
    95: "Slight or moderate Thunderstorm",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail",
    "*": "Code not specified or additional condition",
};
